"""Markdown outputs: model card, risk register, NIST AI RMF mapping, release decision."""

from __future__ import annotations

import re

from readiness.assess import Assessment, RiskResult

ICON = {"GO": "✅", "CONDITIONAL GO": "🟡", "NO-GO": "⛔"}
STATUS_ICON = {"Mitigated": "🟢", "Open": "🔴", "Evidence gap": "🟠", "Accepted": "🔵"}
OUTCOME_ICON = {"pass": "✅", "fail": "❌", "missing": "⚪", "stale": "🕓"}
GENERATED = "<!-- Generated by readiness. Edit config/, not this file. -->"


def _bullets(items) -> list[str]:
    return [f"- {item}" for item in items]


def _sign_off_line(system: dict) -> str:
    s = system.get("sign_off") or {}
    if s.get("approver"):
        return f"Signed off by **{s['approver']}** on {s.get('date') or '—'} as **{s.get('decision') or '—'}**."
    return "**Awaiting human sign-off.** This page is a recommendation; a named approver must accept it in the system card."


def model_card(system: dict, a: Assessment) -> str:
    ev = a.evidence
    latest = ev.latest_run
    lines = [
        GENERATED,
        f"# Model Card — {system['name']}",
        "",
        f"**Release recommendation: {ICON[a.decision]} {a.decision}** · as of {ev.as_of:%Y-%m-%d %H:%M} UTC",
        "",
        "| | |",
        "|---|---|",
        f"| System | {system['name']} (`{system['id']}`) |",
        f"| Version | {system.get('version', '—')} |",
        f"| Owner | {system['owner']} |",
        f"| Repository | {system['repository']} |",
        f"| Approved model | `{system['approved_configuration']['model']}` · prompt `{system['approved_configuration']['prompt_version']}` |",
        f"| Latest evaluation | {latest.run_at:%Y-%m-%d %H:%M} UTC · {latest.n_cases} cases |" if latest else "| Latest evaluation | none |",
        "",
        "## What it does",
        "",
        system["description"].strip(),
        "",
        "## Intended use",
        "",
        *_bullets(system["intended_use"]),
        "",
        "## Out of scope",
        "",
        *_bullets(system["out_of_scope"]),
        "",
        f"**Users:** {system['users']}",
        "",
        f"**Human oversight:** {system['human_oversight'].strip()}",
        "",
        "## Components",
        "",
        "| Component | Detail |",
        "|---|---|",
        *[f"| {c['name']} | {c['detail']} |" for c in system["components"]],
        "",
        "## Evaluation",
        "",
        f"- **Dataset:** {system['evaluation']['dataset']}",
        f"- **Method:** {system['evaluation']['method']}",
        f"- **Cadence:** {system['evaluation']['cadence']}",
        f"- **Runs on record:** {len(ev.runs)} ({len(ev.eligible_runs)} full runs on the approved configuration count as evidence)",
        "",
        "## Key results",
        "",
        "| Metric | Value | Measured |",
        "|---|---|---|",
    ]
    metrics = sorted({c.label.split()[0] for r in a.risks for c in r.checks if " " in c.label and c.label.split()[1] in (">=", "<=", ">", "<")})
    for m in metrics:
        e = ev.metric(m)
        when = f"{e.run.run_at:%Y-%m-%d}" if e.run else "—"
        value = "—" if e.value is None else f"{e.value:.2f}"
        lines.append(f"| {m} | {value} | {when} ({e.status}) |")
    lines += [
        "",
        "## Known limitations",
        "",
        *_bullets(system["known_limitations"]),
        "",
        "## Risk summary",
        "",
        "| Risk | Inherent | Status | Residual |",
        "|---|---|---|---|",
        *[f"| {r.id} {r.risk['title']} | {r.inherent_rating} | {STATUS_ICON[r.status]} {r.status} | {r.residual_rating} |" for r in a.risks],
        "",
        "Full detail: [RISK_REGISTER.md](RISK_REGISTER.md) · [NIST_AI_RMF.md](NIST_AI_RMF.md) · [RELEASE_DECISION.md](RELEASE_DECISION.md)",
        "",
        "## Sign-off",
        "",
        _sign_off_line(system),
        "",
    ]
    return "\n".join(lines)


def _risk_block(r: RiskResult) -> list[str]:
    risk = r.risk
    lines = [
        f"### {r.id} · {risk['title']}",
        "",
        f"{STATUS_ICON[r.status]} **{r.status}** · inherent **{r.inherent_rating}** "
        f"(likelihood {risk['likelihood']} × impact {risk['impact']} = {r.inherent_score}) · residual **{r.residual_rating}**",
        "",
        f"- **Category:** {risk['category']}",
        f"- **Owner:** {risk['owner']}",
        f"- **Control:** {' '.join(str(risk['control']).split())}",
        f"- **NIST AI RMF:** {', '.join(risk['nist'])}",
    ]
    if r.checks:
        lines += ["", "| Evidence | Result | Detail |", "|---|---|---|"]
        for c in r.checks:
            tag = "" if c.required else " *(supporting)*"
            lines.append(f"| {c.label}{tag} | {OUTCOME_ICON[c.outcome]} {c.outcome} | {c.detail} |")
    else:
        lines += ["", "*No automated evidence is defined for this risk.*"]
    acc = risk.get("acceptance")
    if acc:
        lines += [
            "",
            f"> **Risk acceptance** by {acc['by']} on {acc['date']} (review by {acc.get('review_by', '—')}): "
            f"{' '.join(acc['rationale'].split())}",
        ]
    lines += [f"- {n}" for n in r.notes]
    lines.append("")
    return lines


def risk_register(system: dict, a: Assessment) -> str:
    counts = {}
    for r in a.risks:
        counts[r.status] = counts.get(r.status, 0) + 1
    summary = " · ".join(f"{STATUS_ICON[s]} {s}: {n}" for s, n in counts.items())
    lines = [
        GENERATED,
        f"# Risk Register — {system['name']}",
        "",
        f"As of {a.evidence.as_of:%Y-%m-%d %H:%M} UTC · {len(a.risks)} risks · {summary}",
        "",
        "| ID | Risk | Owner | Inherent | Status | Residual |",
        "|---|---|---|---|---|---|",
        *[f"| {r.id} | {r.risk['title']} | {r.risk['owner']} | {r.inherent_rating} ({r.inherent_score}) | {STATUS_ICON[r.status]} {r.status} | {r.residual_rating} |" for r in a.risks],
        "",
        "**Status key:** 🟢 Mitigated — every required check passes on current evidence · 🔴 Open — a required check fails · "
        "🟠 Evidence gap — evidence is missing or stale · 🔵 Accepted — no automated evidence, formally accepted by a named person",
        "",
        "## Detail",
        "",
    ]
    for r in a.risks:
        lines += _risk_block(r)
    return "\n".join(lines)


def nist_mapping(nist: dict, register: dict, a: Assessment) -> str:
    status_by_risk = {r.id: r.status for r in a.risks}
    risks_by_sub: dict[str, list[str]] = {}
    for risk in register["risks"]:
        for sub in risk["nist"]:
            risks_by_sub.setdefault(sub, []).append(risk["id"])
    lines = [
        GENERATED,
        "# NIST AI RMF Mapping",
        "",
        "How this project produces evidence for the NIST AI Risk Management Framework (AI RMF 1.0). "
        "Subcategory text is paraphrased from the NIST AI RMF Playbook.",
        "",
    ]
    for function, subs in nist.items():
        lines += [f"## {function}", "", "| Subcategory | What it asks | How it is covered | Linked risks |", "|---|---|---|---|"]
        for sub_id, item in subs.items():
            linked = risks_by_sub.get(sub_id, [])
            linked_txt = ", ".join(f"{STATUS_ICON[status_by_risk[r]]} {r}" for r in linked) or "—"
            lines.append(f"| **{sub_id}** | {item['text']} | {'; '.join(item['covered_by'])} | {linked_txt} |")
        lines.append("")
    unmapped = sorted(set(risks_by_sub) - {s for subs in nist.values() for s in subs})
    if unmapped:
        lines += ["> ⚠️ Risks reference subcategories not listed above: " + ", ".join(unmapped), ""]
    return "\n".join(lines)


def release_decision(system: dict, a: Assessment) -> str:
    ev = a.evidence
    latest = ev.latest_run
    lines = [
        GENERATED,
        f"# Release Decision — {system['name']}",
        "",
        f"## {ICON[a.decision]} Recommendation: {a.decision}",
        "",
        f"As of {ev.as_of:%Y-%m-%d %H:%M} UTC, for `{system['approved_configuration']['model']}` · prompt `{system['approved_configuration']['prompt_version']}`.",
        "",
        "### Why",
        "",
        *_bullets(a.reasons),
        "",
        "### Evidence base",
        "",
        f"- {len(ev.runs)} evaluation runs on record; {len(ev.eligible_runs)} ran the full test set on the approved configuration and count as evidence",
    ]
    if latest:
        state = ("stopped before every test case ran — excluded" if latest.partial_coverage
                 else "LLM judge stopped part-way — judge metrics from it excluded" if latest.judge_incomplete
                 else "complete")
        lines.append(f"- Latest run: {latest.run_at:%Y-%m-%d %H:%M} UTC ({state}) · its own gate said **{latest.decision}**")
    for run in ev.excluded_runs:
        why = "partial test set" if run.partial_coverage else f"model/prompt {run.model} · {run.prompt_version} is not the approved one"
        lines.append(f"- Excluded: {run.run_at:%Y-%m-%d %H:%M} UTC — {why}")
    lines += [
        f"- Evidence older than {ev.max_age.days} days is treated as stale",
        "- Each metric uses its newest measurement that covered the full test set",
        "",
        "### Rules applied (config/policy.yaml)",
        "",
        "1. ⛔ NO-GO if any open risk is rated high or critical",
        "2. ⛔ NO-GO if a critical risk has no current evidence and is not formally accepted",
        "3. 🟡 CONDITIONAL GO if any risk is open, has an evidence gap, or relies on an acceptance",
        "4. ✅ GO when every risk is mitigated by current evidence",
        "",
        "### Sign-off",
        "",
        _sign_off_line(system),
        "",
    ]
    return "\n".join(lines)


START, END = "<!-- READINESS:START -->", "<!-- READINESS:END -->"


def readme_block(entries: list[tuple[dict, Assessment]]) -> str:
    lines = [
        START,
        f"*Updated {entries[0][1].evidence.as_of:%Y-%m-%d %H:%M} UTC*",
        "",
        "| AI system | Recommendation | 🟢 Mitigated | 🔴 Open | 🟠 Evidence gap | 🔵 Accepted | Governance pack |",
        "|---|---|---|---|---|---|---|",
    ]
    for system, a in entries:
        c = {s: sum(1 for r in a.risks if r.status == s) for s in STATUS_ICON}
        sid = system["id"]
        pack = (f"[Model card](reports/{sid}/MODEL_CARD.md) · [Risks](reports/{sid}/RISK_REGISTER.md) · "
                f"[NIST](reports/{sid}/NIST_AI_RMF.md) · [Decision](reports/{sid}/RELEASE_DECISION.md)")
        lines.append(f"| **{system['name']}** | {ICON[a.decision]} **{a.decision}** | {c['Mitigated']} | {c['Open']} | "
                     f"{c['Evidence gap']} | {c['Accepted']} | {pack} |")
    lines.append("")
    for system, a in entries:
        lines.append(f"- **{system['name']}:** " + "; ".join(a.reasons))
    lines += ["", "📊 Live dashboard: [byshivam.github.io/ai-release-readiness](https://byshivam.github.io/ai-release-readiness/)", END]
    return "\n".join(lines)


def update_readme(text: str, block: str) -> str:
    if START not in text:
        raise ValueError("README has no READINESS markers")
    return re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, count=1, flags=re.S)
